### ISSUE TITLE
Criativo

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#1]
No index.html deves adicionar no parágrafo um texto (pode ser gerado pelo ChatGPT) que fale um pouco da cidade que escolheste!

https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/e3b373fdc9d9a80ddeead5dc5b026339bc7c7a6f/lab2/index.html#L20

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
