### ISSUE TITLE
Remover <br>

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#11]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/a629767ec9062fb170a511645f1668711a717209/lab4/quizz.html#L40

https://ulusofona-interfaces-web.gitbook.io/lab-4/a-minha-cidade-css/eliminar-less-than-br-greater-than

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido.
