### ISSUE TITLE
Precisamos de uma classe nova?

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#15]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/a629767ec9062fb170a511645f1668711a717209/lab4/styles.css#L144C2-L144C9

Sempre que criamos novas classes trazemos complexidade para o CSS, será que não existe outra forma de chegar ao objetivo final que queres?

**Comment by tiago-goncalves-a22201250** [comment]
O meu pensamento quando resolvi esse problema foi ter parametros diferentes para aquilo que pretendo
