### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by spektrier** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#16]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/2bfde2281e64c56ddc68deb168b48fab5427e006/lab4/index.html#L22

Deverias incluir a imagem em todos os ficheiros html do lab 4, não só no index

**Comment by tiago-goncalves-a22201250** [comment]
Fica mais bonito so naquela pagina, mas obrigado pela recomendação.
