### ISSUE TITLE
Issue #2

### ISSUE THREAD

**Issue by spektrier** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#17]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/2bfde2281e64c56ddc68deb168b48fab5427e006/lab4/info.html#L10

No info.html, quizz.html e viagem.html não estás a inserir o nome da tua cidade

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
