### ISSUE TITLE
Uso de <p>

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#18]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/f4ef038dbe90991cb9062e025b3c4c8e32f134a9/lab5/pontosinteresse.html#L40

Não devemos usar <p> aqui, que elemento é que devemos usar?
Dica: Vê os uso de sections no lab 3

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
