### ISSUE TITLE
Precisamos de criar uma div? e uma classe?

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#19]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/f4ef038dbe90991cb9062e025b3c4c8e32f134a9/lab5/pontosinteresse.html#L26C32-L27C17

Será mesmo necessário o uso de uma <div> aqui?
Será que precisamos de uma classe?

**Comment by tiago-goncalves-a22201250** [comment]
Criei para resolver o problema do texto e outro para as referencias.
