### ISSUE TITLE
Uso de grid

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#20]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/f4ef038dbe90991cb9062e025b3c4c8e32f134a9/lab5/capitais.css#L104-L108

Ainda não falamos de grid, será que existe uma forma de fazer isto só com flexbox?

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
