### ISSUE TITLE
O Autor da fotografia deve aparecer dentro do seu article

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#21]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/f4ef038dbe90991cb9062e025b3c4c8e32f134a9/lab5/capitais.html#L40

![image](https://github.com/user-attachments/assets/165fc1b7-4326-4c5b-a1d8-b9d582041cb0)

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
