### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#22]
https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/f4ef038dbe90991cb9062e025b3c4c8e32f134a9/lab5/styles.css#L83

Isto apenas está a ser aplicado à volta da imagem, se for carregar mesmo na imagem aparece o cursor default.

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
