### ISSUE TITLE
Texto alternativo (alt)

### ISSUE THREAD

**Issue by martim-lusofona** [tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io#3]
Todas as imagens devem conter um texto alternativo (alt)

https://github.com/tiago-goncalves-a22201250/tiago-goncalves-a22201250.github.io/blob/e3b373fdc9d9a80ddeead5dc5b026339bc7c7a6f/lab1/report.html#L28

**Comment by tiago-goncalves-a22201250** [comment]
Resolvido
